### ISSUE TITLE
Getting logged out in another window should trigger redirect to login

### ISSUE THREAD

**Issue by mfldavidson** [tl-its-umich-edu/remote-office-hours-queue#213] opened 2020-11-04 14:59 UTC
If I am logged in to ROHQ in one window, and in another window I log out, nothing happens on the original page to tell me that I have been logged out. However, when I click on anything, I get errors that might not make sense to an end user. For example, if I get logged out while sitting on the /manage page, then click on a queue, it gives me `Access Denied: You are not a host of this queue. If you believe you are seeing this message in error, contact the queue host(s).` BUT it still shows me as "logged in" if you look in the upper right--i.e. it shows my uniqname and not a Login button.
![image](https://user-images.githubusercontent.com/31591389/98126452-9daf6a00-1e83-11eb-8161-ebcbd77f126f.png)

The only way to get clarity on what is really going on and get the opportunity to login again is if I manually refresh the page.

Particularly bad if someone thinks they are in line and just waiting for the page to update to say it's their turn, or they are a host watching the queue waiting for someone to join, and they don't realize they've been logged out and thus the page isn't updating.

Ideal would be that getting logged out in another window causes the original window to redirect to Login, maybe with a red error message saying "You have been logged out. Please login again." or something.

**Comment by tayheath** [comment] 2023-03-24 19:14
Hello! I'm currently a student at the University of Michigan in the EECS 481 Software Engineering class and I'd love to try and tackle this issue. I've just recently joined the EECS-481-MyLA google group if you would like to contact me at all. I plan on making a pull request according to the contribution guidelines in a week or so when I complete my implementation of the bug fix!

**Comment by hemashahumich** [comment] 2024-06-14 19:15
Steps to Reproduce the Issue:
I am hoping I have created the steps as per issue described by Maggie.

1. Open two ROHQ windows and log into both simultaneously.
2. In the first ROHQ window:
   - Log in as a visitor.
   - Open a queue and join it.
3. In the second ROHQ window:
   - Log out.
4.  Return to the first ROHQ window and attempt to create a meeting:
    - Click the "Create Meeting" button.
9. Observed Behavior:
   - I am unable to start the meeting when you click the "Create Meeting" button.
   - At the top of the screen, a message saying "Start Meeting" appears, but the meeting does not actually start.
**Screenshot:**
![image](https://github.com/tl-its-umich-edu/remote-office-hours-queue/assets/155757888/2bcf1f55-303c-41b7-9a1f-eaeefe9359cb)

Seeking advice if how should I be testing it?

**Comment by jonespm** [comment] 2024-06-14 19:27
This commit was not yet available for testing so that's likely why you were having this issue.

**Comment by jaydonkrooss** [comment] 2024-06-19 15:59
I discovered that this fix is not working in ROHQ QA. The local storage "loggedIn" variable is never set to true to begin with, so logging out has no effect on other windows. 

To make matters more complicated, when I manually set loggedIn to true and then false in devTools, the app crashed. Here's the logs that I see, but I can't really make sense of what happened: `ERROR 2024-06-19 11:30:24,574 Internal Server Error: /accounts/login`
![Screenshot 2024-06-19 at 11 57 18 AM](https://github.com/tl-its-umich-edu/remote-office-hours-queue/assets/147423601/19c895d8-932c-4df6-b44a-e717b0b55cea)

I've suspected that the code was added to the local login/logout flow doesn't work well with how ROHQ in QA/prod uses the UMich SSO to log in. Reopening this issue until we can get a fix for this, we may want @jxiao21's development branch onto the dev environment to properly test new changes.

**Comment by jonespm** [comment] 2024-06-19 17:28
So sounds like there's two issues

1. window.localStorage.setItem("loggedIn", "true");  is never run on production. This makes sense because it's only when you click the login button.

Even if you don't login, it would still set this to true. I think we need some other way to detect the user is logged in. I'm not sure at the moment how best to do this. 

So when manually running this to set and logging out you get this other error. 

2. If you logout, the windows redirect to `accounts/login` which doesn't exist in prod. This is hardcoded and probably needs to be a variable. I think it needs to be put into the base.html. You might be able to get to that variable with 
`{% url 'auth_logout' %}`

But I'm not 100%. Looks like we did something like that in Student Explorer.  I'd try that out. We'll have to think about that first thing.

**Comment by jxiao21** [comment] 2024-06-19 19:53
Is 'auth_logout' a url that can only be tested if it's in QA? There's no url for 'auth_logout' in any of the urls.py files.

**Comment by jonespm** [comment] 2024-06-19 21:23
Yeah, ignore that auth_logout, that was a URL pattern that was used in Student Explorer. I'd just implement the context processor to get the value from settings.

**Closed** 2024-06-21 14:47 UTC
Labels: bug, good first issue, front end, Effort: 8

**Comment by hemashahumich** [comment] 2024-06-24 20:43
Not sure if the results is expected or not.  Steps followed are as follows:

1. Logged into QA.officehours.it.umich.edu/queue/487
2. Joined the queue, and waiting in the line for the host to admit as seen in the screenshot below.
![image](https://github.com/tl-its-umich-edu/remote-office-hours-queue/assets/155757888/dd641760-f9c9-4bb1-870c-10fb2d6abdb1)
3. Open new tab in browser and logged into QA.officehours.it.umich.edu/queue/487
4.  joined the same queue and see the same screenshot as listed below:
5. 
![image](https://github.com/tl-its-umich-edu/remote-office-hours-queue/assets/155757888/bb9742cd-f665-4e8a-84f4-3bacf240ef9c)
6.  I signed out of the second screen, and it logged me out of both windows. Shouldn't it just close one window and display a message indicating something like you are waiting in a queue in another session in another window, or provide some alert to the attendee? It seems like the attendee lost their spot from the queue and was logged out of both sessions.  - This needs to be revisited. It's unclear if the intention is to log the attendee out of both sessions without alerting them.

**Comment by hemashahumich** [comment] 2024-06-24 21:14
Oh and additionally, the above only applies if you are waiting in the queue; otherwise, it doesn't matter if you are logged out of all open sessions.
