### ISSUE TITLE
GA4 setup need completion

### ISSUE THREAD

**Issue by hemashahumich** [tl-its-umich-edu/remote-office-hours-queue#494] opened 2024-05-21 13:50 UTC
For GA4 setup, we are 7/8 steps complete. The missing step is related to privacy consent, with the setting instructions We need to add this as a new issue for the June release -  

related to privacy consent
https://analytics.google.com/analytics/web/#/a163299747p312490036/admin/setup-assistant/

setting instructions
https://support.google.com/analytics/answer/14275483?hl=en&utm_id=ad

**Comment by jonespm** [comment] 2024-05-31 15:00
This will be implemented similarly to to https://github.com/tl-its-umich-edu/my-learning-analytics/issues/1580

And likely use these patterns https://vpcomm.umich.edu/resources/cookie-disclosure/

**Comment by jonespm** [comment] 2024-05-31 15:00
This is a duplicate of #493 so closing this.

**Closed by jonespm** 2024-05-31 15:00 UTC
