### ISSUE TITLE
Support Multiple Errors in ErrorDisplay Component

### ISSUE THREAD

**Issue by mfldavidson** [tl-its-umich-edu/remote-office-hours-queue#67] opened 2020-05-31 22:10 UTC
If an error is already showing on /manage/<queueid> and another error is triggered, the second error SOMETIMES never shows--it only shows the original error.

It almost seems like some sort of hierarchy of errors, as follows:
1. "user is not a valid user" error takes precedence. If no "user is not a valid user" error, continue
2. "user is already in a meeting" error--if none, continue
etc

#### This is TRUE for these situations (i.e. these have a bug, the second error is suppressed/doesn't show while the first error is there)
- If "user is not a valid user" error is triggered and THEN "user is already in a meeting" error is triggered
- If "user is not a valid user" error is triggered and THEN "queue name must not be more than 100 characters" error is triggered
- If "user is not a valid user" error is triggered and THEN "queue name must not be blank" error is triggered
- If "user is already in a meeting" error is triggered and THEN "queue name must not be blank" error is triggered
- If "user is already in a meeting" error is triggered and THEN "queue name must not be more than 100 characters" error is triggered

#### This is FALSE for these situations (i.e. these are ok, the second error shows when it is supposed to)
- If "user is already in a meeting" error is triggered and THEN "user is not a valid user" error is triggered
- If "queue name must not be blank" error is triggered and THEN "user is already in a meeting" error is triggered
- If "queue name must not be blank" error is triggered and THEN "user is not a valid user" error is triggered
- If "queue name must not be more than 100 characters" error is triggered and THEN "user is not a valid user" error is triggered
- If "queue name must not be more than 100 characters" error is triggered and THEN "user is not a valid user" error is triggered
- If "queue name must not be more than 100 characters" error is triggered and THEN "user is already in a meeting" error is triggered

**Comment by jlost** [comment] 2020-06-04 12:47
I think the most straightforward fix for this is to allow the error dialog to show multiple errors instead of coalescing to the "highest-priority" one. There is also a larger error story to work out with respect to making them more visible if you've scrolled down the page a bit, but let's solve this in the simple and obvious way for now since moving the errors into the proximity of their calling controls is more complicated.

**Comment by bruinc** [comment] 2020-06-16 19:23
Under what conditions would we remove an error banner? If we just add a banner for every error, then the list could get really long with the same errors (e.g. a host tries to set the queue name to be blank or >100 chars multiple times).

**Comment by ksofa2** [comment] 2020-06-29 19:44
Just chatted about this with Camillie a bit. Seems like we should not display duplicate error, naturally. Unclear on when to remove. @teshsopher @mfldavidson thoughts?

**Comment by mfldavidson** [comment] 2020-06-29 20:02
Could we do something like this logic: If error, check if same error is already displaying. If not, display error. If yes, just display the original error. I defer to @teshsopher on the UX principles. Just brainstorming

**Comment by teshsopher** [comment] 2020-06-30 15:46
Since moving the errors near their related fields has technical complexity, these are my current recommendations:

- Duplicate errors definitely shouldn't display

- In terms of when to remove an error: Looking at the list, some of these errors look like ones that would occur in sequence (i.e. Host goes to add another host and "user is not a valid user" is triggered. Then the host goes to change the queue name and triggers the "queue name must not be blank" error).  In these cases, the first occurring error should stop displaying, unless that error is still a problem (e.g. occurs at the same time as the new error). 

- If multiple errors occur at once, I do like Jame's suggestion. In this case, I would recommend indicating the number of errors, and then presenting the errors in a list. For example:

"2 errors occurred:
- Queue name must not be blank
- User is not a valid user"

Optionally, we could add the related field(s) to the error to help users. In this case, the above error may display as:

"2 errors occurred:
- **Queue Name:** Queue name must not be blank
- **Add Host:** User is not a valid user"

**Comment by bruinc** [comment] 2020-07-06 19:24
Update: I now know _why_ this is happening. Long story short, the error that's displayed is the first found error in an ordered array of possible errors. The order of this array is what decides the "hierarchy" phenomenon we see (e.g. `addHostError` comes before `changeNameError` in the array for the Edit page). I'd also like to point out that I haven't been able to reproduce two errors happening at the exact same time, so if anyone has, let me know what you did. Here are my current ideas for solutions:

1. An easy-to-implement solution would be to always list out the errors. In this case, an error from a certain field would only disappear if the user successfully interacts with that same field (e.g. trying to change the queue name to blank, then changing the queue name to a valid name). For this solution, each field's error would be independent from other fields. One drawback of this is that the same kind of error could be duplicated ("invalid uniqname" for both adding a host and adding an attendee).

2. A solution that I'm currently trying to figure out how to do is to clear **all** errors when we're about to do something that could cause an error, like making an API call. This way the error displayed will always be the most recent error, and successfully updating any field would clear any displayed error. I would vote for this option even though it's giving me trouble 😄 

@jlost @mfldavidson @teshsopher 
Any input is greatly appreciated!

**Comment by jlost** [comment] 2020-07-06 22:20
I would suggest doing #1 first, making the ErrorDisplay component take a list of errors in its props, as that would be a positive change in terms of code quality even regardless of UX benefits.

#2 might be worth pursuing afterward, but it raises some questions as it might make sense to show multiple errors in some circumstances but not others. The implementation also seems to run the risk of adding complexity.

**Comment by bruinc** [comment] 2020-07-10 17:54
Merged- closing and moving to QA

**Closed by bruinc** 2020-07-10 17:54 UTC
Labels: bug, enhancement

**Comment by mfldavidson** [comment] 2020-07-27 13:09
Just tested this by doing the following:
1. Attempted to add a participant who was already in the queue > result = error Add Meeting: jmaggiex is already in a meeting. = success
2. Attempted to add a host who has never logged into ROHQ dev > result = error added above Add Meeting error in error banner Add Host: zoomz is not a valid user. Please make sure the uniqname is correct, and that they have logged onto Remote Office Hours Queue at least once. = success
3. Attempted to add a different participant who was already in the queue > result = error message changed to Add Meeting: jmaggie is already in a meeting. = success
4. Attempted to add a different host who has never logged into ROHQ dev > result = error changed uniqname = success

Excellent work @bruinc . This was a really complicated one and the fix you implemented is fantastic! I love the bolded text to clarify which type of error it is. This makes it so much clearer!

The only thing I think we could do to further improve is scroll them back to the top of the page to sort of signify that something changed in the error banner, because when they try to add a different user after the error is already displaying and they get an error, all that changes is the uniqname which may not be obvious. However this would be a new issue and I'm not even sure if it's that big a deal.
